

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "ToggleButtonSwitchPage.xaml.h"




void ::WinRTControls::ToggleButtonSwitchPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///ToggleButtonSwitchPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///ToggleButtonSwitchPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the ToggleButton named 'ToggleButton1'
    ToggleButton1 = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ToggleButton1"));
    // Get the ToggleSwitch named 'ToggleSwitch1'
    ToggleSwitch1 = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ToggleSwitch1"));
    // Get the Button named 'backButton'
    backButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"backButton"));
    // Get the TextBlock named 'pageTitle'
    pageTitle = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pageTitle"));
}

void ::WinRTControls::ToggleButtonSwitchPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(target))->Checked +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRTControls::ToggleButtonSwitchPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ToggleButtonSwitchPage::ToggleButton1_Checked);
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(target))->Unchecked +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRTControls::ToggleButtonSwitchPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ToggleButtonSwitchPage::ToggleButton1_Unchecked);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRTControls::ToggleButtonSwitchPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&ToggleButtonSwitchPage::ToggleSwitch1_Toggled);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

